profile: debug
log:
  level: 5
  format: "text"
  output: "stdout"
  file: "./log/okr.log"
http:
  port: ":8080"
postgres:
  host: "192.168.0.132"
  port: 5432
  user: "okre"
  password: "okre"
  name: "okre"
  ssl: "disable"  