import Head from "next/head";
import Image from "next/image";
import React, { ReactElement } from "react";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Breadcrumb, Button, DatePicker, Layout } from "antd";
import { useRouter } from "next/router";
import MainLayout from "@/components/MainLayout/MainLayout";
import { useDispatch } from "react-redux";
import { userAction } from "../../redux/usersSlice";
import {
  AllPageLayout,
  AllPageBreadcrumb,
  ContainerPage,
} from "@/styles/styles.all";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const dispatch = useDispatch();
  // 退出登录
  const loginOut = () => {
    dispatch(userAction.loginOut());
    router.push("/");
  };
  return (
    <>
      <Head>
        <title>首页</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout style={AllPageLayout}>
        <Breadcrumb style={AllPageBreadcrumb}>
          <Breadcrumb.Item>销售订单</Breadcrumb.Item>
          <Breadcrumb.Item>新增合同</Breadcrumb.Item>
        </Breadcrumb>
        <ContainerPage>
          <div>
            <div>已进入首页</div>
            <Button type="primary" onClick={() => loginOut()}>
              退出登录
            </Button>
          </div>
        </ContainerPage>
      </Layout>
    </>
  );
}

// 指定Layout.
Home.getLayout = (page: ReactElement) => <MainLayout>{page}</MainLayout>;
