// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"github.com/laidingqing/sokr/internal/api"
	"github.com/laidingqing/sokr/internal/repository"
	"github.com/laidingqing/sokr/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitObjectiveAPI(db *gorm.DB) api.ObjectivesAPI {
	iObjectiveRepository := repository.NewObjectiveRepository(db)
	iObjectiveService := service.NewObjectiveService(iObjectiveRepository)
	objectivesAPI := api.NewObjectivesAPI(iObjectiveService)
	return objectivesAPI
}

func InitUserAPI(db *gorm.DB) api.UserAPI {
	iUserRepository := repository.NewUserRepository(db)
	trans := repository.NewTrans(db)
	iUserService := service.NewUserService(iUserRepository, trans)
	userAPI := api.NewUserAPI(iUserService)
	return userAPI
}

func InitUnitAPI(db *gorm.DB) api.UnitAPI {
	iCompanyRepository := repository.NewCompanyRepository(db)
	trans := repository.NewTrans(db)
	iUnitService := service.NewUnitService(iCompanyRepository, trans)
	unitAPI := api.NewUnitAPI(iUnitService)
	return unitAPI
}
